SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- --------------------------------------------------------------------------------------------
create PROCEDURE [dbo].[pdxCreateDBIndexes]
AS
begin transaction

create index IxDB_AuditDate on dxDataAudit(AuditDate)
create unique index IxDB_dxAccountID on dxAccount(ID ASC)
create index        IxDB_dxAccountTransaction              on dxAccountTransaction (TransactionDate,KindOfDocument) INCLUDE ([PK_dxAccountTransaction])
create index        IxDB_dxAccountTransactionAccountPeriod on dxAccountTransaction (FK_dxAccount,FK_dxPeriod)
create index        IxDB_dxAccountTransactionReception     on dxAccountTransaction (KEY_dxReceptionDetail)
create index        IxDB_dxAccountTransactionShipping      on dxAccountTransaction (KEY_dxShippingDetail)
create index        IxDB_dxAccountTransactionRMA           on dxAccountTransaction (KEY_dxRMADetail)
create index        IxDB_dxAccountTransactionEndOfYearTransaction on dxAccountTransaction ([EndOfYearTransaction])INCLUDE ([FK_dxPeriod],[FK_dxAccount],[Amount])
create unique index IxDB_dxAccountType on dxAccountType(ID)
create index        IxDB_dxAssemblyEffectiveDate on dxAssembly(EffectiveDate Desc)
create index        IxDB_dxBankReconciliationStartDate on dxBankReconciliation(StartDate)
create index        IxDB_dxBankReconciliationDetailDate on dxBankReconciliationDetail(TransactionDate Desc)
create index        IxDB_dxBankReconciliationEndDate on dxBankReconciliation(EndDate Desc)
create index        IxDB_dxCashReceiptDate on dxCashReceipt(TransactionDate)
create index        IxDB_dxCashReceiptInvoiceDate on dxCashReceiptInvoice(TransactionDate Desc)
create        index IxDB_dxCertificate on dxCertificate(ObjectType, ObjectName, PrimaryKey)
create unique index IxDB_dxCity on dxCity(ID)
create unique index IxDB_dxClient on dxClient(ID)
create unique index IxDB_dxClientCategory on dxClientCategory(ID)
create index        IxDB_dxClientOrderDate on dxClientOrder(TransactionDate DESC)
create index        IxDB_dxClientOrderDeliveryDate on dxClientOrder(ExpectedDeliveryDate DESC)
create index        IxDB_dxClientOrderDetailDeliveryDate on dxClientOrderDetail(ExpectedDeliveryDate DESC)
create unique index IxDB_dxClientProduct on dxClientProduct(FK_dxClient,FK_dxProduct)
create unique index IxDB_dxControlProperty on dxControlProperty(ID)
create unique index IxDB_dxConversionFactor on dxConversionFactor(UniqueRecord DESC)
create unique index IxDB_dxCountry on dxCountry(ID)
create unique index IxDB_dxCreditApprobation on dxCreditApprobation(ID)
create unique index IxDB_dxCurrency on dxCurrency(ID)
create unique index IxDB_dxCurrencyDetail on dxCurrencyDetail(FK_dxCurrency,FK_dxPeriod)
create index        IxDB_dxDataAudit on dxDataAudit (TableName, PrimaryKeyValue)
create index        IxDB_dxDepositDate on dxDeposit(TransactionDate)
create unique index IxDB_dxDepositDetail on dxDepositDetail(FK_dxDeposit,FK_dxCashReceipt)
create unique index IxDB_dxEntry on dxEntry(KindOfDocument,PrimaryKeyValue)
create unique index IxDB_dxFOB on dxFOB(ID)
create unique index IxDB_dxGL on dxGL(FK_dxAccount,FK_dxPeriod)
create index        IxDB_dxInvoiceDate on dxInvoice(TransactionDate DESC)
create index        IxDB_dxInvoiceDetail on dxInvoiceDetail(PK_dxInvoiceDetail,FK_dxInvoice)
create unique index IxDB_dxJournal on dxJournal(ID)
create index        IxDB_dxJournalEntryDate on dxJournalEntry(TransactionDate)
create unique index IxDB_dxKanban on dxKanban ( FK_dxWarehouse,FK_dxLocation,FK_dxProduct)
create unique index IxDB_dxLanguage on dxLanguage(ID)
create unique index IxDB_dxLocation on dxLocation(ID)
create        index IxDB_dxLinkedRecordDocumentPrimaryKey      on dxLinkedRecordDocument(PrimaryKeyValue)
create        index IxDB_dxLinkedRecordDocumentLinkedTableName on dxLinkedRecordDocument(LinkedTableName)
create        index IxDB_dxMessageCaptionID on dxMessageCaption([ID] ASC)
create        index IxDB_dxMRPPeriodDate on dxMRP (PeriodDate)
create        index IxDB_dxMRPPeriod     on dxMRP (Period)
create unique index IxDB_dxNote on dxNote(ID)
create unique index IxDB_dxPayableInvoice on dxPayableInvoice (ID,FK_dxVendor)
create index        IxDB_dxPayableInvoiceDetail on dxPayableInvoiceDetail(PK_dxPayableInvoiceDetail,FK_dxPayableInvoice)
create index        IxDB_dxPayableInvoiceDate on dxPayableInvoice(TransactionDate DESC)
create unique index IxDB_dxPeriodID             on dxPeriod(ID DESC)
create index        IxDB_dxPeriodAccountingYear on dxPeriod(FK_dxAccountingYear)
create index        IxDB_dxPeriodStartDate      on dxPeriod(StartDate)
create index        IxDB_dxPeriodEndDate        on dxPeriod(EndDate)
create unique index IxDB_dxPriceLevel on dxPriceLevel(ID ASC)
create unique index IxDB_dxProduct on dxProduct(ID ASC)
create index        IxDB_dxProductForecastPerMonth on dxProductForecastPerMonth([Year],[Month])
create index        IxDB_dxProductForecastPerWeek  on dxProductForecastPerWeek ([Year],[Week])
create unique index IxDB_dxProductManagementDate on dxProductProductionDate(FK_dxProduct,Lot)
create index        IxDB_dxProductTransaction                on dxProductTransaction (TransactionDate,KindOfDocument) INCLUDE ([PK_dxProductTransaction])
create index        IxDB_dxProductTransactionPrimaryKeyValue on dxProductTransaction (PrimaryKeyValue Asc, KindOfDocument Asc )
create index        IxDB_dxProductTransactionLink            on dxProductTransaction (LinkedProductTransaction )
create index        IxDB_dxProductTransactionProductLot      on dxProductTransaction (FK_dxWarehouse,FK_dxLocation,FK_dxProduct, Lot,TransactionDate, PhaseNumber, LinkedProductTransaction,PK_dxProductTransaction ) ON [PRIMARY]
create index        IxDB_dxProjectedStockPeriod on dxProjectedStock ( FK_dxProduct, PeriodDate Asc )
create index        IxDB_dxProjectedStockLevel  on dxProjectedStock ( FK_dxProduct, Level Asc )
--create index        IxDB_dxPropertyValueLinkedTableName      on dxPropertyValue ([LinkedTableName]) INCLUDE ([FK_dxProperty],[PrimaryKeyValue],[Value],[FK_dxDomainValue])
create index        IxDB_dxPurchaseOrderDate on dxPurchaseOrder(TransactionDate DESC)
create index        IxDB_dxPropertyName on dxProperty(Name ASC)
create unique index IxDB_dxQuery on dxQuery(ID)
create        index IxDB_dxReceptionDate on dxReception(TransactionDate DESC)
create unique index IxDB_dxReport on dxReport(ID ASC)
create unique index IxDB_dxScaleUnit on dxScaleUnit(ID ASC)
create        index IxDB_dxSchedulerEventStart  on dxSchedulerEvent ( Start DESC )
create        index IxDB_dxSchedulerEventFinish    on dxSchedulerEvent ( Finish DESC )
create        index IxDB_dxSchedulerEventTypeDates on dxSchedulerEvent ( EventType, Start, Finish )
create unique index IxDB_dxShipVia on dxShipVia(ID ASC)
create        index IxDB_dxShippingDate on dxShipping(TransactionDate DESC)
create        index IxDB_dxShippingDetailItem on [dbo].[dxShippingDetail] ([FK_dxProduct] ASC) INCLUDE ( [FK_dxShipping],[Quantity])
create        index IxDB_dxStandardCostHistoryDate on dxStandardCostHistory ( EffectiveDate DESC ) 
create unique index IxDB_dxStandardCostHistoryUnique on dxStandardCostHistory ( FK_dxProduct, EffectiveDate DESC )
create unique index IxDB_dxState on dxState(ID ASC)
create unique index IxDB_dxStatus on dxStatus(ID ASC)
create unique index IxDB_dxTable on dxTable(ID)
create unique index IxDB_dxTax on dxTax(ID)
create unique index IxDB_dxTaxDetail on dxTaxDetail (FK_dxTax,EffectiveDate DESC)
create unique index IxDB_dxTerms on dxTerms(ID)
create unique index IxDB_dxUser on dxUser(ID)
create unique index IxDB_dxUserGroup on dxUserGroup(ID)
create        index IxDB_dxUnpostAccountTransactionEntry on dxUnpostAccountTransaction (Key_dxEntry)
create unique index IxDB_dxVendor on dxVendor(ID)
create unique index IxDB_dxVendorProduct on dxVendorProduct ( FK_dxVendor,FK_dxProduct )
create unique index IxDB_dxWarehouse on dxWarehouse(ID ASC)
create        index IxDB_dxWorkOrderDate on dxWorkOrder (WorkOrderDate ASC )
create        index IxDB_dxWorkOrderStatus on dxWorkOrder (WorkOrderStatus ASC )
create unique index IxDB_dxAction on dxAction(ActionName ASC)
create unique index IxDB_dxComponent on dxComponent(ComponentName ASC)
create unique index IxDB_dxForm on dxForm(FormName ASC)
create unique index IxDB_dxDataSet on dxDataSet(TableName ASC)
create unique index IxDB_dxDataSetField on dxDataSetField(FK_dxDataSet, ColumnName ASC)
create unique index IxDB_dxMessage on dxMessage(MessageName ASC)
create        index IxDB_dxDocumentHistory on dxDocumentHistory(TransactionDate, FK_dxUser, FK_dxApplicationEvent)
Commit
GO
